## docker-compose 
version: "3.7"

services:
  
  



 
  ####################### 
  # RABBIT MQ Messaging #
  #######################

  rabbitmq:
    image: rabbitmq:3.5.3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 90s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=think 
      - RABBITMQ_DEFAULT_PASS=microservices 
    networks:
      - currency-exchange-network
    
  ##############################################################




  ###############################
  # currency-exchange-processor #
  ###############################

  currency-exchange-processor:
    #image: thinkmicroservices/outbound-email-service:latest
    image: currency-exchange-processor
    
    environment: 
     # - spring.main.banner-mode="off"
      - SPRING_RABBITMQ_HOST=rabbitmq
      - logging.level.com.thinkmicroservices=TRACE
      - spring.profiles.active=dev, swagger
       

      
    networks:
      - currency-exchange-network
    ports:
      - 8081:8080

    depends_on:
      - "rabbitmq"
           
   
 


##################
# define network #
##################
networks:
   currency-exchange-network:
 
     
 

    

